# Generated by Django 3.2.16 on 2022-11-13 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='portafolio',
            fields=[
                ('id_portafolio', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='etiquetas/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'ordering': ['id_portafolio'],
            },
        ),
    ]
