# Generated by Django 3.2.16 on 2022-11-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id_about', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=2500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='about/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Quienes somos',
                'verbose_name_plural': 'Quienes somos',
                'ordering': ['id_about'],
            },
        ),
        migrations.CreateModel(
            name='feature',
            fields=[
                ('id_feature', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=2500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='feature/%Y/%m/%d')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Caracteristica',
                'verbose_name_plural': 'Caracteristicas',
                'ordering': ['id_feature'],
            },
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicios', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=2500)),
                ('icono', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['id_servicios'],
            },
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='portafolio/%Y/%m/%d'),
        ),
    ]
