# Generated by Django 3.2.16 on 2022-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20221113_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='portafolio',
            name='descripcion',
            field=models.CharField(default=1, max_length=2500),
            preserve_default=False,
        ),
    ]
